version: 2.1

orbs:
  go: circleci/go@1.7.1

jobs:
  checkout-and-list:
    resource_class: small
    docker:
    - image: cimg/base:stable
    steps:
    - checkout
    - persist_to_workspace:
        root: "."
        paths: [main.go]
    - run:
        command: "find ."
    
  build:
    resource_class: small
    docker:
    - image: cimg/base:stable
    steps:
    - go/install
    - attach_workspace:
        at: /tmp/workspace
    - run:
        command: "go build -o /tmp/workspace/runme /tmp/workspace/main.go"
    - persist_to_workspace:
        root: /tmp/workspace
        paths: [runme]
    
  run:
    resource_class: small
    docker:
      - image: cimg/base:stable
    steps:
    - attach_workspace:
        at: /tmp/workspace
    - run:
        command: "/tmp/workspace/runme"
    - store_artifacts:
        path: "/tmp/workspace/runme"

workflows:
  checkout-and-build:
    jobs:
      - checkout-and-list
      - build:
          requires:
            - checkout-and-list
      - run:
          requires:
            - build
