version: 2.1

orbs:
  go: circleci/go@1.7.1

jobs:
  checkout-and-list:
    resource_class: small
    docker:
    - image: cimg/base:stable
    steps:
    - checkout
    - run:
        command: "find ."
    
  build:
    resource_class: small
    docker:
    - image: cimg/base:stable
    steps:
    - go/install
    - run:
        command: "go build -o runme main.go"
    
  run:
    resource_class: small
    docker:
      - image: cimg/base:stable
    steps:
    - run:
        command: "./runme"

workflows:
  checkout-and-build:
    jobs:
      - checkout-and-list
      - build:
          requires:
            - checkout-and-list
      - run:
          requires:
            - build
